const types = {
  SET_THEME: "SET_THEME",
  SET_ACTIVE_PRODUCT: "SET_ACTIVE_PRODUCT",
  ADD_PRODUCT_TO_SHOPPING_CART: "ADD_PRODUCT_TO_SHOPPING_CART",
  DELETE_CART_ITEM: "DELETE_CART_ITEM",
  CART_VALUES_REVERT_ON_DELETE: " CART_VALUES_REVERT_ON_DELETE",
  CLEAR_CART: "CLEAR_CART",
  ON_INCREASE_QTY_ITEM: " ON_INCREASE_QTY_ITEM",
  ON_DECREASE_QTY_ITEM: "ON_DECREASE_QTY_ITEM",
};

export default types;
